# modifications to the belt-node8-service GitLab CI file to insert Notifications Hub system tests between deployment to INT and PRD

stages:
  - build
  - publish
  - deploy-int
  - system-tests
  - deploy

system-tests:
  stage: system-tests
  before_script: []
  script:
    - apk add --no-cache curl
    - curl -X POST -F "token=$CI_JOB_TOKEN" -F ref=master https://cimpress.githost.io/api/v4/projects/2836/trigger/pipeline
  only:
    - master
  except:
    - schedules

deploy-int:
  stage: deploy-int
