image: node:8

before_script:
  - echo "@cimpress-technology:registry=https://artifactory.cimpress.io/artifactory/api/npm/npm-release-local/" > ~/.npmrc
  - echo "//artifactory.cimpress.io/artifactory/api/npm/npm-release-local/:_authToken=${CT_ARTIFACTORY_NPM_TOKEN}" >> ~/.npmrc
  - export VERSION=${CI_COMMIT_SHA:0:7}

stages:
  - build
  - publish

build:
  stage: build
  script:
    - npm install
    - npm run coverage
  coverage: '/Branches\s*:\s*(\d*\.?\d+)%/'
  artifacts:
    paths:
      - coverage/

publish:
  stage: publish
  script:
    - npm config set @cimpress-technology:registry=https://artifactory.cimpress.io/artifactory/api/npm/npm-release-local/
    - npm i @cimpress-technology/version-bumper -g
    - bump-version
    - add-keywords "${DEFAULT_KEYWORDS}"
    - npm publish
  only:
    - master
