image: node:10

before_script:
  - echo "@cimpress-technology:registry=https://artifactory.cimpress.io/artifactory/api/npm/npm-release-local/" > ~/.npmrc
  - echo "//artifactory.cimpress.io/artifactory/api/npm/npm-release-local/:_authToken=${CT_ARTIFACTORY_NPM_TOKEN}" >> ~/.npmrc
  - npm i -g grunt
  - npm ci
  - export VERSION=${CI_COMMIT_SHA:0:7}

stages:
  - build
  - publish
  - deploy

build:
  stage: build
  script:
    - npm test
  coverage: '/All files\s*\|\s*[.?\d]+\s*\|\s*([0-9.]+)/'
  artifacts:
    paths:
      - coverage/

dependency_scanning:
  image: briangweber/docker-node:10
  stage: build
  allow_failure: true
  variables:
    # NOTE: Breaking change introduced in v11.11 of the runner, using this
    # feature flag makes newest versions behave like versions prior v11.11
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/4306#note_177127898
    # Orders' runner use v12.3.0 whereas FI' runner use v11.0.0
    FF_USE_LEGACY_VOLUMES_MOUNTING_ORDER: "true"
  services:
    - docker:18-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]

publish:
  image: briangweber/docker-node:10
  stage: publish
  script:
    - grunt bundle --packageVersion=$VERSION --packageName=$CI_PROJECT_NAME
  only:
    - master
  except:
    - schedules

deploy-int:
  stage: deploy
  environment:
    name: integration
  script:
    - grunt deploy --environment=int --packageVersion=$VERSION --packageName=$CI_PROJECT_NAME
  only:
    - master
  except:
    - schedules

deploy-prd:
  stage: deploy
  environment:
    name: production
  script:
    - grunt deploy --environment=prd --packageVersion=$VERSION --packageName=$CI_PROJECT_NAME
  when: manual
  only:
    - master
  except:
    - schedules
