include:
  - template: Dependency-Scanning.gitlab-ci.yml

image: node:10

before_script:
  - echo "@cimpress-technology:registry=https://artifactory.cimpress.io/artifactory/api/npm/npm-release-local/" > ~/.npmrc
  - echo "//artifactory.cimpress.io/artifactory/api/npm/npm-release-local/:_authToken=${CT_ARTIFACTORY_NPM_TOKEN}" >> ~/.npmrc
  - export VERSION=${CI_COMMIT_SHA:0:7}

stages:
  - build
  - publish

build:
  stage: build
  script:
    - npm ci
    - npm test
  coverage: '/All files\s*\|\s*[.?\d]+\s*\|\s*([0-9.]+)/'
  artifacts:
    paths:
      - coverage/

dependency_scanning:
  stage: build

publish:
  stage: publish
  script:
    - npm config set @cimpress-technology:registry=https://artifactory.cimpress.io/artifactory/api/npm/npm-release-local/
    - npm i @cimpress-technology/version-bumper -g
    - bump-version
    - add-keywords "${DEFAULT_KEYWORDS}"
    - npm publish
  only:
    - master
  except:
    - schedules
