variables:
  NODE_OPTIONS: "--max_old_space_size=4096"
  BUCKET_SUFFIX:

.node: &node-common
  before_script:
    - echo "//artifactory.cimpress.io/artifactory/api/npm/npm-release-local/:_authToken=${CT_ARTIFACTORY_NPM_TOKEN}" >> .npmrc
    - npm ci
.python: &py-common
  before_script:
    - pip install awscli
  cache:
    paths:
      - pip-cache

stages:
  - test
  - build
  - deploy

test:
  <<: *node-common
  image: node:10
  stage: test
  script:
    - npm run test

build-rev:
  <<: *node-common
  image: node:10
  stage: build
  artifacts:
    name: "REV_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build
    expire_in: 1 day
  variables:
    REACT_APP_ROUTER_BASENAME: /review/${CI_COMMIT_REF_SLUG}
    PUBLIC_URL: /review/${CI_COMMIT_REF_SLUG}
  except:
    - master
  environment:
    name: review-$CI_COMMIT_REF_SLUG
  script:
    - export NODE_ENV="production"
    - npm run clean
    - cp ./config/int.config .env
    - npm run build

build-int:
  <<: *node-common
  image: node:10
  stage: build
  artifacts:
    name: "INT_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build
    expire_in: 1 day
  only:
    - master
  script:
    - export NODE_ENV="production"
    - cp ./config/int.config .env
    - npm run build

build-prd:
  <<: *node-common
  image: node:10
  stage: build
  artifacts:
    name: "PRD_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build
    expire_in: 1 week
  only:
    - master
  script:
    - export NODE_ENV="production"
    - cp ./config/prd.config .env
    - npm run build

deploy-rev:
  <<: *py-common
  image: python:latest
  stage: deploy
  except:
    - master
  variables:
    DOMAIN_NAME:
    S3_DEST: s3://int-$BUCKET_SUFFIX/review/$CI_COMMIT_REF_SLUG/
  environment:
    name: review-$CI_COMMIT_REF_SLUG
    url: https://$DOMAIN_NAME/review/$CI_COMMIT_REF_SLUG/index.html
  dependencies:
    - build-rev
  script:
    - aws s3 cp ./build $S3_DEST --recursive --exclude "index.html"
    - aws s3 cp ./build/index.html $S3_DEST --cache-control "max-age=0"

deploy-int:
  <<: *py-common
  image: python:latest
  stage: deploy
  only:
    - master
  variables:
    DOMAIN_NAME:
  environment:
    name: INT
    url: https://$DOMAIN_NAME
  dependencies:
    - build-int
  script:
    - aws s3 cp ./build s3://int-$BUCKET_SUFFIX --recursive --exclude "index.html"
    - aws s3 cp ./build/index.html s3://int-$BUCKET_SUFFIX --cache-control "max-age=0"

deploy-prd:
  <<: *py-common
  image: python:latest
  stage: deploy
  only:
    - master
  variables:
    DOMAIN_NAME:
  environment:
    name: PRD
    url: https://$DOMAIN_NAME
  when: manual
  dependencies:
    - build-prd
  script:
    - aws s3 cp ./build s3://prd-$BUCKET_SUFFIX --recursive --exclude "index.html"
    - aws s3 cp ./build/index.html s3://prd-$BUCKET_SUFFIX --cache-control "max-age=0"
