#deploy components for Bean stalk deployment. 
#Using this will require deploycomponents.yaml  

publish:
  image: briangweber/docker-node:carbon
  stage: publish
  script:
    - grunt bundle --packageVersion=$VERSION --packageName=$CI_PROJECT_NAME
  only:
    - master
  except:
    - schedules

deploy-int:
  extends: .deploy
  stage: deploy-int
  variables:
    CI_ENVIRONMENT_NAME: integration

deploy-prd:
  extends: .deploy
  stage: deploy-prd
  variables:
    CI_ENVIRONMENT_NAME: production
  when: manual  