#Base components for setting up a deploy configuration. 

.migrate:
  script:
    - cp -r $CI_PROJECT_DIR/sql/* /flyway/sql/
    - sh /flyway/flyway -url=jdbc:postgresql://$POSTGRES_SERVER:5432/$POSTGRES_DB -schemas=public -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -placeholders.ENVIRONMENT=$DEPLOYENV migrate

.deploy:
  script:
    - grunt deploy --environment=$CI_ENVIRONMENT_NAME --packageVersion=$VERSION --packageName=$CI_PROJECT_NAME
  only:
    - master
  except:
    - schedules